// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:67fbf045-e6c1-49ce-a979-372cea3d3cbe',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'taper-hosting-mobilehub-1249723223',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2bnxzg0969e3w.cloudfront.net',
    'aws_mobile_analytics_app_id': 'eb2d0cf0c3e34f338e061907bc9497b7',
    'aws_project_id': '7ad2aedf-0e93-41d9-ab6a-a9b4e5c33d92',
    'aws_project_name': 'taper-2018-01-14-14-49-36',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'taper-mobilehub-1249723223',
}

export default awsmobile;
